### ISSUE TITLE
Support Backing up Mods/etc Folders

### ISSUE THREAD

**Issue by Kaiede** [Kaiede/Bedrockifier#28]
This could be done adding something like this in the configuration file:

```
java:
    - name: <container name>
      extras:
        - <folder path>
      worlds:
        - <world path>
```

The result would be a series of zip files. So if I had a container called “minecraft_server” and the world was “Yosemite”, the result would be:

minecraft_server.extras.Timestamp.zip
Yosemite.Timestamp.zip

Inside the extras zip would be each folder that was listed in the extras part of the configuration.
