### ISSUE TITLE
[Suggestion] More advanced backup / trimming options

### ISSUE THREAD

**Issue by DanTheMan827** [Kaiede/Bedrockifier#37]
I see that backup events have been added, but I have a couple suggestions to improve it further

- Only backup on interval if there has been or is an active player since the last interval backup (why backup when there's no way a change would've been made?)
- Have the option to trim event backups separately (to limit space usage in case someone logs in and out rapidly)
  - Further expanding on this scenario, if a backup is being made because of the last logout and another backup is in progress for the same reason, that should probably be aborted, the partial file deleted, and a new one made (maybe?)

Even though no one may have played on the server in a few days, backups are made like clockwork at the interval configured, this is _fine_ for the most part but it's a waste of space to backup files that haven't changed.

**Comment by Kaiede** [comment]
The first item is something I can put on the backlog for sure. Good opportunity to hook into the ‘list’ command as well to ensure that we know how many players are logged in when the service starts (just in case the two containers are not started at the same time like it currently assumes). 

The second is something the service handles by throttling the backups taken, rather than trimming after the fact. Trimming after the fact would be pretty wasteful of resources (disk and CPU in particular). This is the purpose of the `minInterval` setting. It ensures only one backup is made during that minimum interval from either `interval` or event-based backups, but it doesn’t affect dailies. Under that sort of model, I do the following on my own server:

```
schedule:
  daily: 1:30 # Ensure we get at least one snapshot before the nightly upload to B2
  minInterval: 3h # Ensure we get no more than 8 backups a day from events
  onPlayerLogout: true # Take opportunistic backups when players log out
```

Another example using interval:

```
schedule:
  interval: 12h # Make sure we have at least 2 backups a day when there isn’t much activity
  minInterval: 3h # Ensure we get no more than 8 backups a day by waiting 3h since the last backup to start a new one.
  onPlayerLogout: true # Take opportunistic backups when players log out
```

Does this not work for the scenario you envision? If there’s something missing, lets identify what it is so I can track that in a separate issue (to not overload this one). 

> if a backup is being made because of the last logout and another backup is in progress for the same reason, that should probably be aborted, the partial file deleted, and a new one made (maybe?)

Good catch, because the code now uses Swift Concurrency, I don’t have the benefit of serial queues anymore which would prevent multiple backups from running simultaneously. But there’s other mechanisms I can use to block that.  I’ve opened #39 to track work to fix that. 

That said, if a backup is already in progress, I believe it’s better to simply complete the old one and abort the new one. The server has already frozen the filesystem state at that point, so aborting, resuming the save, telling the server to flush again, is a rather messy way to ensure you capture the most recent snapshot. I’d much rather err on the side of simpler logic (for reliability) than try to get too clever here, if that makes sense.
