### ISSUE TITLE
Trimming not working properly?

### ISSUE THREAD

**Issue by DanTheMan827** [Kaiede/Bedrockifier#38]
I have this as my config.yml

```yml
containers:
  bedrock:
    - name: mcbedrock
      worlds:
        - "/server/worlds/Rad World - Redux"
        - "/server/worlds/Rad World"
schedule:
  interval: 3h
trim:
  trimDays: 2
  keepDays: 7
  minKeep: 1
loggingLevel: trace
```

Per my understanding of the documentation, I should end up with 16 hourly backups for the last day with every day thereafter trimmed to the latest backup.

However, it doesn't appear to have been trimming the hourly backups for the previous days... I set it to 7 keepDays just to test though and it did properly trim the files to that max number of days (although still every 3 hours for each day)
