### ISSUE TITLE
Backups Fail on Docker Desktop for Windows

### ISSUE THREAD

**Issue by nakanotti** [Kaiede/Bedrockifier#48]
**Describe the bug or issue being faced**
I had an error occured every backup time.
ex)
```
[error   ] Unable to access world path at '/backups/world.20220425-141732.mcworld'
```

Why throw exception always here?
<Sources/Bedrockifier/Model/World.swift>
```
public struct World {
    public enum WorldType {
        case folder
        case mcworld
        case javaBackup

        init(url: URL) throws {
            let isDirectory = try WorldType.isDirectory(url: url)
```
The url is '/backups/world.20220425-141732.mcworld'.
These backup files will seem to successful...
But, throw exception "not a directory" to failure process.

**Configuration  and Verbose Logs**
config.yml:
```
containers:
  bedrock:
    - name: aaa
      worlds:
        - /data/worlds/world

schedule:
  daily: 04:00
  startupDelay: 2m
  onPlayerLogin: true
  minInterval: 2m
trim:
  trimDays: 2
  keepDays: 14
  minKeep: 14
loggingLevel: trace
```

**Additional context**
Log:
```
aaa-backup-1  | [14:17:32.982][info    ] Starting Backup of worlds for: aaa (ContainerConnection.swift:124)
aaa-backup-1  | [14:17:32.982][trace   ] Data Received on file descriptor (3) (Terminal.swift:296)
aaa-backup-1  | [14:17:32.982][trace   ] Processing Listener (Terminal.swift:318)
aaa-backup-1  | [14:17:32.983][trace   ] Data Received on file descriptor (3) (Terminal.swift:296)
aaa-backup-1  | [14:17:32.983][trace   ] Processing Listener (Terminal.swift:318)
aaa-backup-1  | [14:17:32.986][info    ] Backing Up: world (ContainerConnection.swift:130)
aaa-backup-1  | [14:17:46.551][error   ] Unable to access world path at '/backups/world.20220425-141732.mcworld' (ContainerConnection.swift:134)
aaa-backup-1  | [14:17:46.551][error   ] Backup of world at /data/worlds/world failed. (ContainerConnection.swift:135)
aaa-backup-1  | [14:17:46.551][error   ] Backups for aaa had failures... (ContainerConnection.swift:155)
```

Thank you for your help.

**Comment by Kaiede** [comment]
This looks like there might be some permissions related error at play here, where the file is created and written to, but cannot be read from. It's not throwing because the file isn't a directory, but because it can't determine _if it is a directory_. i.e. something's blocking reading the file's attributes.

Can you share your docker-compose.yml, and `ls -l` on the backup files (the mcworld files) that are being created on the host so we can see what user is winding up owning them, and how the service is configured? Also, parts of the verbose log from the start would be helpful here as well, as it would give an idea of what permissions the service is running with.

**Comment by nakanotti** [comment]
I also first suspected access rights.
I entered the CLI and checked it, but I was able to access it as a file without any problems.

Since the world data is large, I will try to make the minimum configuration that can be confirmed to be reproduced.

```
root@e8bd8f3c3d5b:/# ls -al /backups
total 585836
drwxrwxrwx 1 root root      4096 Apr 26 13:53 .
drwxr-xr-x 1 root root      4096 Apr 26 13:45 ..
-rwxrwxrwx 1 root root       272 Apr 25 14:16 config.yml
-rw-r--r-- 1 root root 599890209 Apr 26 13:50 world.20220426-134955.mcworld
```

[aaa-backup-1.log](https://github.com/Kaiede/Bedrockifier/files/8559974/aaa-backup-1.log)

<docker-compose.yml>
```
version: "3"

services:
  aaa:
    container_name: aaa
    image: itzg/minecraft-bedrock-server
    ports:
      - "19136:19136/udp"
    tty: false
    stdin_open: true
    restart: on-failure:1
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock"
      - "./data:/data"
    environment:
      TZ: "Asia/Tokyo"
      LANG: "ja_JP.UTF-8"
      LANGUAGE: "ja_JP"
      SERVER_NAME: "AAA World"
      SERVER_PORT: "19136"
      EULA: "TRUE"
      LEVEL_TYPE: "default"
      LEVEL_NAME: "world"
      GAMEMODE: "survival"
      DIFFICULTY: "hard"
      ALLOW_CHEATS: "true"
      MAX_PLAYERS: "20"
      ONLINE_MODE: "true"
      ALLOW_LIST: "false"
      DEFAULT_PLAYER_PERMISSION_LEVEL: "visitor"
    labels:
      - manymine.enable=true
    networks:
      - proxy_default

  backup:
    image: kaiede/minecraft-bedrock-backup
    restart: on-failure:1
    depends_on:
      - "aaa"
    environment:
      TZ: "Asia/Tokyo"
      LANG: "ja_JP.UTF-8"
      LANGUAGE: "ja_JP"
    tty: true
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock"
      - "./backups:/backups"
      - "./data:/data"
    networks:
      - proxy_default

networks:
  proxy_default:
    external: true
```

**Comment by Kaiede** [comment]
I can also make changes so that the underlying error is more completely reported, and push that out to the test tag which will give us more details and help diagnose similar issues in the future. I’ll do that tomorrow.  

And yes, it does look like the backup is being made okay. But somehow the file then can’t be checked to confirm we got a valid backup afterwards. Strange. It’s possible that something about the size of the backup is somehow triggering a bug in Swift on Linux that will need to be worked around.

**Comment by nakanotti** [comment]
I found successful case...

<docker-compose.yml>
```
  volumes:
#   - "./backups:/backups" ... throw exception in "Docker Desktop for Windows".
      - "aaa-backups:/backups" # using docker volumes

volumes:
  aaa-backups:
```
It may be a problem due to the permissions of Windows local folder!
