### ISSUE TITLE
Can't debug error: The operation could not be completed. No such file or directory

### ISSUE THREAD

**Issue by jarrettv** [Kaiede/Bedrockifier#51]
**Describe the bug or issue being faced**
I've tried using your tool twice now and keep getting hung up at the beginning. The trace logging doesn't help debug the error. The `unhealthy` file exists in the backups folder and there is no indication which file or directory is failing.

**Verbose Logs**
```
DEBU[0000] Using /backups to match uid and gid 
DEBU[0000] Resolved 1000 from environment variable UID
DEBU[0000] Resolved 1000 from environment variable GID 
The operation could not be completed. No such file or directory
[INFO] sleeping 24h...
```

**config.yml**
```
containers:
  bedrock:
    - name: minecraft-bds
      worlds:
        - "/server/worlds/s2"
schedule:
  interval: 3h
trim:
  trimDays: 2
  keepDays: 14
  minKeep: 2
loggingLevel: trace
```

**docker-compose.yml**
```
  backup:
    image: kaiede/minecraft-bedrock-backup
    container_name: minecraft_backup
    restart: always
    depends_on:
      - "minecraft-bds"
    environment:
      - TZ
      - UID=${PUID}
      - GID=${PGID}
    tty: true
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ${USERDIR}/docker/minecraft-bedrock-backup/backups:/backups
      - ${USERDIR}/docker/minecraft/season2:/server
```
