### ISSUE TITLE
No such file or directory

### ISSUE THREAD

**Issue by djryan012** [Kaiede/Bedrockifier#52]
**Describe the bug or issue being faced**
I know this has come up before in closed issues. I have have tried this over the last few months including using your two-bedrock example verbdom with both and reducing it down to just one server. I believe my logs show correct permission for all folders as far as im concerned. Based on others error logs my setup is not able to find the config file. I understand basics of docker and have had itzg bedrock docker running for over a year but not able to backup automatically. Any advice to what I have wrong would be apreciated.

Docker Compose
```
version: '3.7'

services:
  backup:
    image: kaiede/minecraft-bedrock-backup
    restart: always
    depends_on:
      - "private"
    environment:
      TZ: "America/Los_Angeles"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - /volume2/bedrock/backups:/backups
      - /volume2/bedrock/private:/bedrock_private
    stdin_open: true  #added cause I was getting stdin detached

  private:
    image: itzg/minecraft-bedrock-server:latest
    restart: always
    container_name: bedrock_private
    environment:
      EULA: "TRUE"
      GAMEMODE: survival
      DIFFICULTY: normal
      VERSION: "1.18.33.02"
    ports:
      - 60601:60601/udp
    volumes:
      - /volume2/bedrock/private:/data
    stdin_open: true
    tty: true
```
**Configuration**
```
containers:
  bedrock:
    # Backup the world "PrivateSMP" on the "bedrock_private" docker container
    - name: bedrock_private
      worlds:
        - "/private/worlds/PrivateSMP"
schedule:
  # This will perform a backup every 3 hours.
  # At most this will generate 8 backups a day.
  interval: 3h
trim:
  # Keep all backups for the last two days (today and yesterday)
  # Keep at least one backup for the last 14 days
  # Keep at least two backups per world
  trimDays: 2
  keepDays: 14
  minKeep: 2
loggingLevel: trace
```
**Verbose Logs**
Have tried adding trace and debug in config with neither showing any different information. Just a repeated error of 4 lines below.
```
DEBU[0000] Using /backups to match uid and gid          
DEBU[0000] Resolved UID=999 from match path             
DEBU[0000] Resolved GID=999 from match path             
The operation could not be completed. No such file or directory
```

**Additional context**
My Docker server is running on a Asustor NAS and im using Portainer to manage it but that shouldnt be reason for issue.
![docker permissions](https://user-images.githubusercontent.com/29285175/172072469-f6f0ab77-44a2-4f34-946c-e7131698f7a6.png)
