### ISSUE TITLE
two-bedrock-interval

### ISSUE THREAD

**Issue by ozhally** [Kaiede/Bedrockifier#55]
Thank you so much for this tool.
I am trying to get it going on my Docker on my Synology and admit I am a novice.

I am running two Minecraft worlds and attempting to backup both.
The issue is the second world backup is not outputing the file in a mcworld format.

The first world backup exports the world perfectly as a *.mcworld, (/volume1/docker/Backup/Hallys Temple.*etc*.mcworld).
But then the second world is placed insde a subfolder in a compressed file format (/volume1/docker/Backup/Dreamwyn 07/12/2SH1JA~F).

Obviously, the backup of the second world is functional for restoring purposes but I thought you maybe interested in the output naming structure of the secondary world.

Here is my docker-compose.yml for reference;
```
version: '3.7'

services:
  backup:
    image: kaiede/minecraft-bedrock-backup
    restart: unless-stopped
    depends_on:
      - "Hallys_1st"
      - "Dreamwyn"
    environment:
        TZ: "Australia/Brisbane"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - /volume1/docker/Backup:/backups
      - /volume1/docker/Minecraft/1st:/Hallys_1st
      - /volume1/docker/Minecraft/Dreamwyn:/Dreamwyn
    
  manymine:
    image: illiteratealliterator/manymine
    restart: unless-stopped
    container_name: manymine
    ports:
      - '19135:19132/udp'
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
  
  Hallys_1st:
    image: itzg/minecraft-bedrock-server
    restart: unless-stopped
    container_name: Hallys_1st
    environment:
       server-name: "Hallys 1st"
       gamemode: "survival"
       difficulty: "peaceful"
       allow-cheats: "false"
       max-players: "12"
       online-mode: "true"
       white-list: "false"
       view-distance: "32"
       tick-distance: "12"
       player-idle-timeout: "60"
       max-threads: "0"
       level-name: "Hallys Temple"
       level-seed: "2029492581"
       default-player-permission-level: "visitor"
       texturepack-required: "false"
       motd: "Hallys 1st Server"
       version: "LATEST"
       UID: "1028"
       GID: "100"
       EULA: "TRUE"
       ENABLE_AUTOPAUSE: "TRUE"
       PATH: "/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin"
       TZ: "Australia/Brisbane"
    ports:
      - 19132:19132/udp
    volumes:
      - /volume1/docker/Minecraft/1st:/data
    stdin_open: true
    tty: true
    labels:
      - manymine.enable=true

  Dreamwyn:
    image: itzg/minecraft-bedrock-server
    restart: unless-stopped
    container_name: Dreamwyn
    environment:
       PATH: "/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin"
       max-players: "12"
       UID: "1028"
       GID: "100"
       VERSION: "LATEST"
       DIFFICULTY: "peaceful"
       GAMDEMODE: "survival"
       ONLINE_MODE: "true"
       SERVER_NAME: "Dreamwyn"
       EULA: "TRUE"
       ENABLE_AUTOPAUSE: "TRUE"
       allow-cheats: "false"
       white-list: "false"
       view-distance: "32"
       tick-distance: "12"
       player-idle-timeout: "60"
       max-threads: "0"
       level-name: "Dreamwyn"
       default-player-permission-level: "visitor"
       texturepack-required: "false"
       MOTD: "Dreamwyn Server"
       TZ: "Australia/Brisbane"
    ports:
      - 19142:19132/udp
    volumes:
      - /volume1/docker/Minecraft/Dreamwyn:/data
    stdin_open: true
    tty: true
    labels:
      - manymine.enable=true
```

And then my config.yml;
```
containers:
  bedrock:
    - name: Hallys_1st
      worlds:
        - /Hallys_1st/worlds/Hallys Temple
    - name: Dreamwyn
      worlds:
        - /Dreamwyn/worlds/Dreamwyn
schedule:
  interval: 3h
trim:
  trimDays: 2
  keepDays: 14
  minKeep: 2
```

Thanks
