### ISSUE TITLE
Help with "SSH connection doesn't seem to have been made properly"

### ISSUE THREAD

**Issue by klaborda** [Kaiede/Bedrockifier#80]
**Describe the bug or issue being faced**
When setting up my server with this backup service, I am noticing an `error` that I cannot pinpoint.  It looks like the backup service cannot connect to my minecraft server, but I'm not sure what I'm missing at this point (I've tried to eliminate some things after reading the docker compose docs but... still no luck).  Any help or pointers would be greatly appreciated!

**Configuration  and Verbose Logs**
Please attach your `config.yml` and verbose logs to more quickly help.

_docker-compose.yml_
```
version: "3.8"

services:
  backup:
    image: kaiede/minecraft-bedrock-backup
    restart: always
    # Make sure the minecraft image starts before the backup
    depends_on:
      - "minecraft"
    environment:
        # Useful for making sure your logs have a proper timestamp
        TZ: "America/Denver"
    volumes:
      # Map your backups folder info /backups
      - /docker/minecraft-backups:/backups
      # Map your server's data folder
      - /docker/minecraft-data:/public

  minecraft:
    image: itzg/minecraft-server
    # Expose SSH port to the backup container
    expose:
      - 2222
    tty: true
    stdin_open: true
    ports:
      - "25565:25565"
    environment:
      EULA: "TRUE"
      ENABLE_SSH: "TRUE"
      TYPE: "FABRIC"
      DIFFICULTY: "hard"
      MAX_PLAYERS: "5"
      SEED: "5103687417315433447"
      SERVER_NAME: "MY NAME"
      MOTD: "MY MOTD"
      RCON_PASSWORD: "SECRETHERE"
      MEMORY: "4G"
      TZ: "America/Denver"
    volumes:
      # attach the relative directory 'data' to the container's /data path
      - /docker/minecraft-data:/data
    restart: unless-stopped
```
_config.yml_
```
loggingLevel: trace
containers:
  java:
    - name: minecraft
      # Tells the backup service that this container is accessible
      # using the mc-server-runner SSH functionality.
      # passwordFile should point to the .rcon-cli.yaml file in the container
      ssh: minecraft:2222
      passwordFile: /public/.rcon-cli.yaml
      # Backup the world in the "minecraft_public" container
      # Backup the logs and mods folder into an "extras.zip"
      worlds:
        - /public/world
      extras:
        - /public/logs
        - /public/mods
schedule:
  # This will trigger a backup every time the last player logs out.
  # At most, one backup every 4 hours will be made when the player logs out.
  # There is also one daily backup made at 1am every day.
  # This will produce a maximum of 7 backups a day, but will always produce
  # one daily backup.
  daily: 01:00
  onLastLogout: true
  minInterval: 4h
trim:
  # Keep all backups for the last two days (today and yesterday)
  # Keep at least one backup for the last 14 days
  # Keep at least two backups per world
  trimDays: 2
  keepDays: 14
  minKeep: 2
```

_Logs from minecraft server and network status_
```
root@dock:~/docker/minecraft# docker compose logs minecraft | grep 2222
minecraft-1  | 2024-02-11T19:57:55.296-0700	INFO	mc-server-runner	Starting remote shell server on 2222...
root@dock:~/docker/minecraft# docker ps
CONTAINER ID   IMAGE                                 COMMAND                  CREATED         STATUS                          PORTS                                                     NAMES
03a8edf18225   kaiede/minecraft-bedrock-backup       "/opt/bedrock/entry.…"   4 minutes ago   Up 4 minutes (healthy)                                                                    minecraft-backup-1
9d303b4bd3b7   itzg/minecraft-server                 "/start"                 4 minutes ago   Up 4 minutes (healthy)          2222/tcp, 0.0.0.0:25565->25565/tcp, :::25565->25565/tcp   minecraft-minecraft-1
```

_Logs from backup_
```
root@dock:~/docker/minecraft# docker compose logs -f backup
backup-1  | /usr/sbin/deluser: The user `bedrockifier' does not exist.
backup-1  | time="2024-02-11T19:57:47-07:00" level=debug msg="Using /backups to match uid and gid"
backup-1  | time="2024-02-11T19:57:47-07:00" level=debug msg="Resolved UID=1000 from match path"
backup-1  | time="2024-02-11T19:57:47-07:00" level=debug msg="Resolved GID=1000 from match path"
backup-1  | [19:57:47.015][info    ] Initializing Bedrockifier Daemon
backup-1  | [19:57:47.017][info    ] Configuring Bedrockifier Daemon
backup-1  | [19:57:47.017][info    ] Loading Configuration From: /backups/config.yml
backup-1  | [19:57:47.020][info    ] Configuration Loaded, Running Service... (main.swift:117)
backup-1  | [19:57:47.029][debug   ] Creating Java Container Connection. (container: minecraft (ContainerConnection.swift:398)
backup-1  | [19:57:47.030][info    ] Host PTY Handle Opened: /dev/pts/0  (minecraft - 5) (Terminal.swift:150)
backup-1  | [19:57:47.030][info    ] Child PTY Handle Opened: /dev/pts/0 (minecraft - 7) (Terminal.swift:171)
backup-1  | [19:57:47.030][debug   ] Process attached (Terminal.swift:90)
backup-1  | [19:57:47.030][debug   ] Starting Terminal Process. (container: minecraft, kind: ssh) (ContainerConnection.swift:97)
backup-1  | [19:57:47.031][debug   ] Expecting: ["SSHPASS: detected prompt. Sending password.", "SSHPASS: read:"] (minecraft) (Terminal.swift:277)
backup-1  | [19:57:47.031][trace   ] Adding Expectation FA6FDD09-B8BE-49F1-91E6-112056BDC630 (minecraft) (Terminal.swift:315)
backup-1  | [19:57:47.031][debug   ] Timeout for Expectation is 60.0 s (minecraft) (Terminal.swift:321)
backup-1  | [19:57:47.043][trace   ] Process terminated (executable: file:///usr/bin/sshpass (Process.swift:41)
backup-1  | [19:57:47.043][debug   ] Calling process detach handlers (minecraft) (Terminal.swift:103)
backup-1  | [19:57:47.043][debug   ] Process detached (minecraft) (Terminal.swift:108)
backup-1  | [19:57:47.044][trace   ] Data Received on file descriptor (minecraft - 5) (Terminal.swift:346)
backup-1  | [19:57:47.044][trace   ] Processing 1 Expects (minecraft) (Terminal.swift:361)
backup-1  | [19:57:47.044][debug   ] Content Read: ssh: connect to host minecraft port 2222: Connection refused
backup-1  |  (minecraft) (Terminal.swift:286)
backup-1  | [19:57:47.045][trace   ] Content Has No Matches (minecraft) (Terminal.swift:291)
backup-1  | [19:58:47.031][debug   ] Timeout Reached for FA6FDD09-B8BE-49F1-91E6-112056BDC630 (Terminal.swift:326)
backup-1  | [19:58:47.032][trace   ] Removing Expectation FA6FDD09-B8BE-49F1-91E6-112056BDC630 (minecraft) (Terminal.swift:302)
backup-1  | [19:58:47.032][debug   ] No Matches Found, Timed Out (minecraft) (Terminal.swift:295)
backup-1  | [19:58:47.032][error   ] SSH connection doesn't seem to have been made properly. (ContainerConnection.swift:109)
backup-1  | [19:58:47.032][debug   ] Docker Process Window Size Fetched. (cols = 65000, rows = 24 (ContainerConnection.swift:376)
backup-1  | [19:58:47.032][info    ] Checking for servers that might not be cleaned up (BackupActor.swift:91)
backup-1  | [19:58:47.033][info    ] Backup Time: 01:00 (Service.swift:175)
backup-1  | [19:58:47.034][info    ] Next Backup: Feb 12, 2024, 1:00:00 AM (Service.swift:182)
backup-1  | [19:58:47.034][debug   ] [interval] Scheduled For Feb 12, 2024, 1:00:00 AM (ServiceTimer.swift:73)
backup-1  | [19:58:47.034][info    ] Starting Listeners for Containers (Service.swift:201)
backup-1  | [19:58:47.034][info    ] Backup Minimum Interval is 14400.0 seconds (Service.swift:100)
backup-1  | [19:58:47.035][info    ] Service Started Successfully. (Service.swift:108)
backup-1  | [19:58:47.035][debug   ] [interval] Registered (ServiceTimer.swift:102)
```

**Additional context**
I was previously using some `container_name`'s but dropped that to try and reduce the variables at play.  At this point, I feel like the naming convention should work right, but I feel like I'm just missing something obvious or something.
For what it's worth, I'm running this on a LXC running docker on my Proxmox box on my LAN.  I can connect to the minecraft server just fine (and I figured I should have some backups for my world), so I wanted to try and integrate this!
