### ISSUE TITLE
[BUG] Problems with config.yml

### ISSUE THREAD

**Issue by Jorgeluisreis** [Kaiede/Bedrockifier#89]
When creating docker-compose with the bedrock server and the backup system, an error occurs regarding config.yml, in addition to not creating the backup folder.

![image](https://github.com/Kaiede/Bedrockifier/assets/81347105/cd3eed63-f4b4-4617-bbdd-7ada125b2519)

```
services:
  mundinho-docker:
    container_name: mundinho-docker
    image: itzg/minecraft-bedrock-server:latest
    restart: unless-stopped
    environment:
      EULA: "TRUE"
      # Nome do mundo
      LEVEL_NAME: "Mundinho"

      # Nome do Server
      SERVER_NAME: "Mundinho"

      # Mensagem de Boas-vindas
      MOTD: "Bem vindos ao Mundinho!"

      # Máximo de Plauers
      MAX_PLAYERS: "4"

      # Seed
      LEVEL_SEED: "mundinho"

      # Senha do Servidor
      PASSWORD: "2024"

      # Habilitar Skins Personalizadas
      DISABLE_CUSTOM_SKINS: "false"

      # Dificuldade do mundo
      DIFFICULTY: "normal"

      # Gamemode do mundo
      GAMEMODE: "0"  # Survival

      # Spawn de monstros
      SPAWN_MONSTERS: "true"  # Ativado

      # Spawn de animais
      SPAWN_ANIMALS: "true"  # Ativado

      # Spawn de NPCs
      SPAWN_NPCS: "false"  # Desativado

      # Blocos de comando
      COMMAND_BLOCK_ENABLED: "false"  # Desativado

      # Geração de estruturas
      LEVEL_TYPE: "default"

      #Distancia e Tick de Renderização
      VIEW_DISTANCE: "12"
      TICK_DISTANCE: "12"

      # Permitir que o jogador "Haalks" se junte ao jogo como operador
      OPS: "2535436030075026" #Haalks

    volumes:
      - ./servidor:/data #Dados do Servidor
    ports:
      - "19132:19132/udp"

    stdin_open: true
    tty: true

  backup-mundinho:
    container_name: backup-mundinho
    image: kaiede/minecraft-bedrock-backup:latest
    restart: always
    depends_on:
    - "mundinho-docker" # Server
    volumes:
    - /var/run/docker.sock:/var/run/docker.sock
       # Mapeando a pasta do Servidor
    - /.servidor:/server
        # Mapeando pasta de Backup
    - /.backup-mundinho:/backups
```
